parameters:
    ten24_marcato_integration.cache_provider.class: 'Ten24\MarcatoIntegrationBundle\Service\CacheProvider'
    ten24_marcato_integration.downloader.class: 'Ten24\MarcatoIntegrationBundle\Service\Downloader'
    ten24_marcato_integration.parser.array.class: 'Ten24\MarcatoIntegrationBundle\Service\ArrayParser'
    ten24_marcato_integration.parser.entity.class: 'Ten24\MarcatoIntegrationBundle\Service\EntityParser'
    ten24_marcato_integration.synchronizer.class: 'Ten24\MarcatoIntegrationBundle\Service\Synchronizer'
    ten24_marcato_integration.command.synchronization.class: 'Ten24\MarcatoIntegrationBundle\Command\SynchronizationCommand'
    ten24_marcato_integration.command.cache.clear.class: 'Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand'
    ten24_marcato_integration.cache_warmer.class: 'Ten24\MarcatoIntegrationBundle\CacheWarmer\MarcatoDataCacheWarmer'
    ten24_marcato_integration.datetime_handler.class: 'Ten24\MarcatoIntegrationBundle\Serializer\Handler\DateHandler'

services:
    # Downloader
    ten24_marcato_integration.downloader:
        class: %ten24_marcato_integration.downloader.class%
        arguments:
            - %ten24_marcato_integration.organization_id%
            - %ten24_marcato_integration.feeds.configuration%

    # Entity parser
    ten24_marcato_integration.parser.entity:
        class: %ten24_marcato_integration.parser.entity.class%
        arguments:
            - @jms_serializer.serializer

    # Default parser is entity
    ten24_marcato_integration.parser.default:
        alias: ten24_marcato_integration.parser.entity

    # Synchronizer
    ten24_marcato_integration.synchronizer:
        class: %ten24_marcato_integration.synchronizer.class%
        arguments:
            - @ten24_marcato_integration.downloader
            - @ten24_marcato_integration.parser.default
            - @doctrine.orm.entity_manager
            - %ten24_marcato_integration.feeds.configuration%

    # Cache Clear Command as a service (used in Sync Command)
    ten24_marcato_integration.command.cache.clear:
        class: %ten24_marcato_integration.command.cache.clear.class%
        calls:
            - [ setContainer, [@service_container] ]

    # Sync Command
    ten24_marcato_integration.command.synchronization:
        class: %ten24_marcato_integration.command.synchronization.class%
        tags:
            -  { name: console.command }

    # Cache Warmer - todo/not implemented
    #ten24_marcato_integration.cache_warmer:
    #    class: %ten24_marcato_integration.cache_warmer.class%
    #    arguments:
    #        - @ten24_marcato_integration.synchronizer
    #    tags:
    #        - { name: kernel.cache_warmer }

    # Custom Deserialization DateTime Handler
    # The Marcato data uses nil=true but JMS looks in the xsi:nil attr namespace for it.
    ten24_marcato_integration.datetime_handler:
        class: %ten24_marcato_integration.datetime_handler.class%
        tags:
            - { name: jms_serializer.subscribing_handler }

    # Repositories
    # @todo - this is requiring the proxy service for the laziness...maybe it can be fixed?
    ten24_marcato.repository.artist:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        lazy: true
        arguments:
            - Ten24\MarcatoIntegrationBundle\Entity\Artist

    ten24_marcato.repository.performance:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Ten24\MarcatoIntegrationBundle\Entity\Performance